### ISSUE TITLE
MULTIPOLYGON CSV import

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-DataTypeGeometry#7]
I run into an issue with a CSV where some MULTIPOLYGONS give an error like:
```
2022-04-17T22:21:08+00:00 ERR (3): InvalidArgumentException: Invalid geometry (getGeometryFromValue): MULTIPOLYGON (((4.71738271964073 52.0163279512106, 4.7172997588009 52.0166213573658, 4.71785736667223 52.0166998597818, 4.71790275009395 52.0165701977848, 4.71793698535659 52.0164826261556, 4.71795503647406 52.0164250529558, 4.71738271964073 52.0163279512106, 4.71734570718631 52.0165574129289, 4.71735184117507 52.0165318120359, 4.71739586908315 52.0165358277755, 4.71738973511897 52.0165614286709, 4.71734570718631 52.0165574129289))) in /home/***/omeka-s-3.1.2/modules/DataTypeGeometry/src/DataType/Geometry.php:54
Stack trace:
#0 /home/***/omeka-s-3.1.2/modules/DataTypeGeometry/src/DataType/AbstractDataType.php(89): DataTypeGeometry\DataType\Geometry->getGeometryFromValue()
#1 /home/***/omeka-s-3.1.2/application/src/Api/Representation/ValueRepresentation.php(68): DataTypeGeometry\DataType\AbstractDataType->getJsonLd()
#2 [internal function]: Omeka\Api\Representation\ValueRepresentation->jsonSerialize()
#3 /home/***/omeka-s-3.1.2/modules/CSVImport/src/Job/Import.php(784): json_encode()
#4 /home/***/omeka-s-3.1.2/modules/CSVImport/src/Job/Import.php(424): CSVImport\Job\Import->updateRevise()
#5 /home/***/omeka-s-3.1.2/modules/CSVImport/src/Job/Import.php(296): CSVImport\Job\Import->update()
#6 /home/***/omeka-s-3.1.2/modules/CSVImport/src/Job/Import.php(194): CSVImport\Job\Import->processBatchData()
#7 /home/***/omeka-s-3.1.2/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
#8 /home/***/omeka-s-3.1.2/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send()
#9 /home/***/omeka-s-3.1.2/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send()
#10 {main} {"userId":3,"jobId":742}
```

What I don't understand is why/how the value gets altered, because in the example above, the value in the CSV is:
`MULTIPOLYGON (((4.71738271964073 52.0163279512106, 4.7172997588009 52.0166213573658, 4.71785736667223 52.0166998597818, 4.71790275009395 52.0165701977848, 4.71793698535659 52.0164826261556, 4.71795503647406 52.0164250529558, 4.71738271964073 52.0163279512106)),((4.71734570718631 52.0165574129289, 4.71735184117507 52.0165318120359, 4.71739586908315 52.0165358277755, 4.71738973511897 52.0165614286709, 4.71734570718631 52.0165574129289)))`

So, somewhere along the line the ")),((" is replace with a "," and the MULTIPOLYGON becomes invalid.

When I enter the MULTIPOLYGON via the admin GUI the value is stored unaltered.

Another thing I don't understand is why the CSV import is using the DataTypeGeometry module as I didn't define the type of the geo:asWKT property in the Resource template (so should be just a literal).

**Comment by Daniel-KM** [comment]
Multipolygon/multiline/multipoint are not managed for now.
